version: '3'
networks:
  rabbitMQ:
    name: topic_rabbitMQ
    external: true
    driver: bridge

  backend:
    name: topic_backend
    external: true
    driver: bridge

services:
  worker:
    container_name: comment-worker
    build: .
    networks:
      - rabbitMQ
      - backend
  